-- no. of friends
DELIMITER $$
CREATE PROCEDURE number_of_friends()
BEGIN
	SELECT User_ID,COUNT(DISTINCT Friend_ID) 	FROM Friends GROUP BY User_ID;
END
$$ DELIMITER ;

-- proc: friend user cmts for a specific post
-- DEMO PROC

DELIMITER $$
CREATE PROCEDURE COMM1(IN P INT)
BEGIN
	SELECT POSTS.POST_ID,POSTS.POSTED_USER_ID,POSTS.POST_CONTENT,POST_COMMENTS.COMMENTED_USER_ID,POST_COMMENTS.COMMENT_CONTENT FROM POSTS INNER JOIN POST_COMMENTS ON POSTS.POST_ID=POST_COMMENTS.POST_ID WHERE POSTS.POST_ID=P;
END $$
DELIMITER;